services:
  fenrir:
    image: fenrir
    container_name: fenrir
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: "America/Sao_Paulo"
      DNSMASQ_LISTENING: all
      FTLCONF_dns_listeningMode: "all"
    volumes:
      - ./data/etc-pihole/:/etc/pihole/
      - ./data/etc-dnsmasq.d/:/etc/dnsmasq.d/
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
